### PR TITLE
Add sodre as a maintainer

### PR DESCRIPTION
**Pull request by sodre**
Hi @curtlh, please add me as a comaintainer.

Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by CurtLH** [comment]
@conda-forge-admin, please update team

**Comment by CurtLH** [comment]
I'm not sure why, but I don't have write access to merge pull requests in this repo, even though I'm [listed as a maintainer](https://github.com/conda-forge/pytorch-pretrained-bert-feedstock/blob/master/recipe/meta.yaml#L50).

Any thoughts on what the issue might be @conda-forge/core?

image

**Comment by scopatz** [comment]
Sometimes it takes a while and you may need to accept an invite

**Comment by CJ-Wright** [comment]
Actually it seems that there wasn't a team made for this? (yet?) @conda-forge/pytorch-pretrained-bert

**Comment by CurtLH** [comment]
@CJ-Wright -- I double checked to see if maybe I misspelled my username or accidentally included a trailing space, but that doesn't appear to be a problem.

**Comment by jakirkham** [comment]
@conda-forge-admin, please update team.

Edit: I forget whether this works in PRs or not.

Edit 2: It needs to be done in an issue. Handle with issue ( https://github.com/conda-forge/pytorch-pretrained-bert-feedstock/issues/3 )

**Comment by jakirkham** [comment]
Can you please recheck @CurtLH?

**Comment by CurtLH** [comment]
I'm not sure if it's just coincidence, or if someone did something, but I just got the email that I've been added.  Thanks for your help @scopatz @CJ-Wright @jakirkham

**Comment by jakirkham** [comment]
I asked the bot to update the team. It must have had issues before.

**Pull request merged**
